### ISSUE TITLE
getProportionateScreenHeight and getProportionateScreenWidth returns an error

### ISSUE THREAD

**Issue by lurdharry** [abuanwar072/E-commerce-App-UI-Flutter#6]
whenever I call the function.
I got the error below.

flutter: The method 'toDouble' was called on null.
flutter: Receiver: null
flutter: Tried calling: toDouble()

I noticed that 

  **screenWidth = _mediaQueryData.size.width;
    screenHeight = _mediaQueryData.size.height;**

these data return null

**Comment by abuanwar072** [comment]
Please call SizeConfig.init(conttext) on your starting screen.
